### ISSUE TITLE
Saving login password does not work with Firefox

### ISSUE THREAD

**Issue by LudovicRousseau** [movim/movim#193] opened 2016-05-24 06:57 UTC
Even if my account password is saved by Firefox (46.0.1 on Mac OS X) the password is not presented again on the next login.
I am not sure it is a problem with movim itself. Safari (9.1.1) is able to propose the saved password for example.

Maybe Movim is using a construction that Firefox does not understand or like.

I am using the Movim installation at https://it.movim.eu/

**Comment by edhelas** [comment] 2016-05-24 20:49
It does work for me on Firefox 45 ESR on Debian and on Chrome.
Can you reproduce it on another similar configuration ?

**Comment by LudovicRousseau** [comment] 2016-05-26 08:41
I have the same problem with Iceweasel (Firefox) 38.8.0 on Debian stable.

If I use the Firefox "reload page" button I noticed that I get an error message displayed and removed just after (not easy to read).
The message is "Movim cannot talk with the server, please try again later (Websocket connection error)".
I will check my XMPP (Prosody) logs.

**Comment by LudovicRousseau** [comment] 2016-05-26 16:10
I checked my Prosody logs and I have **NO** new log entry when I reload the page and get the "Movim cannot talk with the server, please try again later (Websocket connection error)" error.

I changed the Prosody server log level from "info" to "debug" but I do not get any log entry either. It looks like the server is not even contacted.

I am using prosody 0.9.7-2+deb8 from Debian stable.

**Comment by edhelas** [comment] 2016-05-26 20:54
The error displayed at the beginning has no link with this issue at all. The error is just displayed before the Websocket connection.

For the second message, that's perfectly normal. Movim is "just" a webclient, like a webmail for your email server but for XMPP. If you reload the page, Movim is doing nothing to the XMPP server. The Websocket is just connected to the web server where Movim is hosted, that's all.

**Comment by edhelas** [comment] 2016-08-24 19:43
After a couple of tries under several OS and browsers I was not able to reproduce the issue. I'm closing the ticket.

**Closed as completed by edhelas** 2016-08-24 19:43 UTC
Labels: more info
