### ISSUE TITLE
Line separating new messages in a chatroom shown under first unread message

### ISSUE THREAD

**Issue by KillyMXI** [movim/movim#586] opened 2018-01-17 10:54 UTC
![](https://i.imgur.com/vTnsJQm.png)

Expected behaviour: dashed line is a separator between read and unread messages.
Observed behaviour: dashed line is an underline for the first unread message.

**Comment by edhelas** [comment] 2018-01-19 11:28
Are you sure that this is happening all the time? And not only under certain circumstances (that I cannot reproduce for now).

**Comment by KillyMXI** [comment] 2018-01-19 11:33
Looks like it happens some times more often then the others.
My best guess atm is that it's more likely to happen with human comments than with bot messages.

**Comment by edhelas** [comment] 2018-08-03 13:38
The line will appears above the bubble that contains the first unread message. But bubbles group up messages that are published by the same person within the same minute.
Closing the ticket.

**Closed as completed by edhelas** 2018-08-03 13:38 UTC
Labels: more info
