### ISSUE TITLE
Messages are duplicated in chat log

### ISSUE THREAD

**Issue by VsyachePuz** [movim/movim#174] opened 2016-04-22 18:59 UTC
<img src="http://i.imgur.com/WTqEazg.png" />

**Comment by edhelas** [comment] 2016-04-23 06:51
Is there a way to reproduce it ?

**Comment by VsyachePuz** [comment] 2016-04-23 07:13
They are perfectly reproducible. When I close browser and reopen it again, this messages are still duplicated.

You are asking me to install my own instance of Pod and debug it myself, and fix it myself, and provide a PR, not less than that, or what?
I am unable to say the reason of this issue more exactly, because I don't know php.

**Comment by edhelas** [comment] 2016-04-23 20:37
Calm down.

Closing and opening again your browser is not a way to reproduce the issue, it just makes the same issue disappears and appears again.

When I'm asking you how you can reproduce it, I'm not asking you to solve it (by doing PHP, that's my job) nor installing a new instance.

What I'm asking you, and what I've asked to all the previous guys that have reported issues on Movim before is under what circumstances theses issues appears. Then I can reuse theses circumstances to try to reproduce them on my local computer with a different account and a different setup to check if this issue appears again and if it's caused by Movim or something around.

So, if you can reproduce this issue, with a different XMPP account or using another Movim server and explains me with details what you have done, this could helps me to solve this ticket.

For the moment I simply don't have enough information to help you.

**Comment by VsyachePuz** [comment] 2016-04-23 23:16
I think this happens when (my) messages comes from XMPP-client (instead of web browser).
I didn't do something special, just registered a user, added you as a contact, started chat with you, and wrote you several messages.

**Comment by ludwikbukowski** [comment] 2016-05-30 09:46
I think I had the same issue:
Way to reproduce:
- create two accounts e.g _user1@domain_  and _user2@domain_
- login on _user1@domain_
- go to http://10.100.13.11/?contact and add contact _user2@domain_
- got to http://10.100.13.11/?chat/
- click on _plus button_ and choose start new conversation
- choose "Load more contacts"
- choose _user2@domain_
- type a message and send
- click (or sometimes double click) on the contact _user2@domain_ on the left panel

![duplicated](https://cloud.githubusercontent.com/assets/6969609/15646011/b6402728-265b-11e6-9968-4326d3f6edf3.png)

-when you click, the last few messages are duplicated. Seems that number of duplicated messages increases by one every duplication

**Comment by edhelas** [comment] 2016-05-30 20:52
Thanks for the feedback but unfortunately I can't reproduce the issue :( What XMPP server do you have and what is the domain ? Do you have MAM enabled ? Is it possible to have the credentials of a buggy account ?

**Comment by ludwikbukowski** [comment] 2016-06-03 10:08
XMPP server: mongooseim
XMPP domain: _erlang-solutions.com_
XMPP user: _test.esl.user@erlang-solutions.com_
**MAM enabled**, but always returns empty message list (database backend is not configured on the server side).  **When I disabled MAM the problem dissapeared**
For now, the movim instance is running in our internal company network but soon will be available to the public so you could test it if you want

## 

**[EDIT]**
running movim instance available here http://31.172.186.62/

**Comment by edhelas** [comment] 2016-06-09 21:16
Hi, thanks for the feedback so your issue seems related to #33. However I'm still curious to know why MAM create such issue in Movim (there is normally ids to prevent this kind of duplication).

**Comment by edhelas** [comment] 2017-02-15 21:48
The chat backend has been totally refactored, I never experienced the issue again since then. Closing the ticket.

**Closed as completed by edhelas** 2017-02-15 21:48 UTC
Labels: more info
