### ISSUE TITLE
Focus input field after clicking "Reply"

### ISSUE THREAD

**Issue by ltguillaume** [movim/movim#1217] opened 2023-07-06 16:05 UTC
With the new context menu for posts (Add a reaction, Reply, Copy the text), the input field isn't focused after clicking Reply.

**Comment by edhelas** [comment] 2023-07-09 10:09
It is actually, thanks to this line https://github.com/movim/movim/blob/master/app/widgets/Chat/Chat.php#L891

I cannot reproduce your issue.

**Comment by ltguillaume** [comment] 2023-07-09 10:39
It consistently did(n't) do so for the last 2-3 days, and now it _does_ focus the input field. Strange stuff. Is this yet another issue with script caching perhaps? I have no such issues with any other web app, except for Movim: changes often aren't (fully) present unless I log off an log on again (which makes no sense, because I'm not even logged on to begin with).

**Comment by edhelas** [comment] 2023-07-09 10:40
This code didn't changed recently. So its weird.
Is it on mov.im ? Did you force reload ?

**Comment by ltguillaume** [comment] 2023-07-09 10:45
Yeah, mov.im. I "force-reload" every time I use Movim, really: every time I start it, I create a fresh profile by copying only the files `Login Data`, `Preferences`,  `Secure Preferencs`, and `Web Data` (which only predefines search engines) on a RAM-disk. So while I thought about caching, there really isn't any way this could be a factor, as there's no local storage, no indexdb, not even a cookie that's being saved between sessions in my case.

**Comment by edhelas** [comment] 2023-07-09 10:48
But why ?
Movim is not meant to be cleared each time like this.
The issue is elsewhere and I have no clue how to reproduce it.

**Comment by ltguillaume** [comment] 2023-07-09 10:50
Ok this is interesting. Could you explain why Movim would take issue with being cleared like this? Why would it matter and cause issues then? It's just like logging in on a new browser/machine.

**Comment by edhelas** [comment] 2023-07-09 11:02
Because there is cache for performance optimisation and stuff that can be sometimes put in local storage.
But its not related to this.

I can't reproduce your issue so I'm putting this ticket as Wont Fix.

If you need to follow up on this ticket lets chat on the main chatroom.

**Closed as completed by edhelas** 2023-07-09 11:02 UTC
Labels: wontfix, more info

**Comment by ltguillaume** [comment] 2023-07-09 11:09
> I can't reproduce your issue so I'm putting this ticket as Wont Fix.

Yes makes sense. If the issue returns _and_ I can provide more data, I'll revisit it in the chatroom.
