### ISSUE TITLE
(Cosmetic) Long names in chat list overflow

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#452] opened 2017-09-06 07:14 UTC
If the name of a contact is too long, it is abbreviated in the chat list. However, the icon next to the name (e.g. mobile, web, ...) is not taken into account and overflows into the neighbouring timestamp.

**Comment by edhelas** [comment] 2017-09-10 20:37
This seems to be caused by a rendering issue on Chrome based browsers.

**Comment by Natureshadow** [comment] 2017-09-11 07:55
Like, the official Movim client apps ;)?

**Comment by edhelas** [comment] 2017-09-11 09:12
Yes exactly, the Android and desktop apps are relying on Chrome :)

**Comment by edhelas** [comment] 2017-10-28 09:19
Closing this ticket.

**Closed as completed by edhelas** 2017-10-28 09:19 UTC

**Comment by Natureshadow** [comment] 2017-10-28 09:53
> Closing this ticket.

Umm, because…?
