### ISSUE TITLE
TypeError: items.forEach is not a function

### ISSUE THREAD

**Issue by mirabilos** [movim/movim#746] opened 2018-12-16 20:44 UTC
items.forEach(item => item.classList.remove('active'));

chats.j...3771365 (Zeile 20, Spalte 21)

**Comment by edhelas** [comment] 2018-12-16 22:47
What browser are you using? would it be possible to give more information when you're opening a ticket and use English?

**Comment by mirabilos** [comment] 2018-12-16 23:03
Jaussoin Timothée dixit:

>What browser are you using?

Firefox 45 ESR, Linux/i386 official Mozilla binaries.

>would it be possible to give more information when you're opening a
>ticket and use English?

Yes, sorry. I was a bit in a hurry and thought I could add the infos
later, as I’m currently trying to help @Natureshadow debug why the
new version does not work, and it turns out this is taking longer
than I thought.

These four errors have popped up in the Firebug error console while
trying to do things on the Web UI. (The numbers are line/column, I
changed them in the other reports but forgot that here.)

**Comment by edhelas** [comment] 2018-12-19 07:10
As I know you had server issues. This can generate faulty HTML, the JS is relying on the presence of this HTML, therefore this issue is caused by the backend issue that need to be solved and not a JS issue.

Same here :)
Let's solve this PHP/session/backend issue ;)

Also Firefox 45 was released in March 8, 2016, there was other LTS releases since then. I'm not supporting old browsers like that on Movim.

**Closed as completed by edhelas** 2018-12-19 07:10 UTC
Labels: wontfix, more info
