### ISSUE TITLE
Chat input doesn't get refocused after switching windows

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#272] opened 2016-10-21 13:30 UTC
Expected behavior:
- Open a Chat with a contact
- Chat input gets focused
- Change window to anything else so the navigator loses focus
- Come back to the navigator
- Chat input gets re-focused

Actual behavior:
- Chat input doesn't get re-focused when coming back on the page

Same behavior on both Firefox Nightly (52.0a1) and Chromium (53.0.2785.143).
Maybe it is something to be expected I'm not sure, but it's quite annoying here.

**Comment by edhelas** [comment] 2016-11-06 20:01
I can't reproduce it, the input is actually correctly focused.
https://github.com/movim/movim/blob/master/app/widgets/Chat/chat.js#L343

**Comment by edhelas** [comment] 2017-02-15 21:42
Closing the issue

**Closed as completed by edhelas** 2017-02-15 21:42 UTC
Labels: more info
