### ISSUE TITLE
Keep the scroll state after removing the keyboard on mobile

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#303] opened 2016-11-10 00:28 UTC
## Steps

1. Go to any chat tab with more than a full screen of messages.
2. Scroll to the bottom
3. Focus the text input (virtual keyboard appears)
4. Unfocus the input (back button, or press somewhere in the chat) to make the virtual keyboard disappear.

## Expected result

Chat scroll back at previous position.

## Actual result

Chat scrolls back at previous position minus keyboard size apparently, not sure it's accurate.

**Comment by edhelas** [comment] 2017-02-15 21:21
I cannot reproduce this issue, the scrolling stays at the same position for me after your steps (on Android 6.0 and the native Android app).

**Comment by edhelas** [comment] 2017-03-08 07:11
Closing this ticket

**Closed as completed by edhelas** 2017-03-08 07:11 UTC
Labels: more info

**Comment by Ppjet6** [comment] 2017-10-02 01:37
This still happens on `568e2d17` (master). Using Firefox Nightly on Android 7.1.2. I was probably using the default browser when I first opened the thread though.

This means I have to scroll down if I want to see any new message each time I type a message and I hide the keyboard again.

**Comment by Ppjet6** [comment] 2017-12-27 21:47
Seems to be fixed in b1b51144 (master), not sure when exactly. Thanks!
