### ISSUE TITLE
Private posts not working

### ISSUE THREAD

**Issue by kvaps** [movim/movim#402] opened 2017-06-19 08:44 UTC
Steps for reproduce:
- Go to communities
- Create new post (don't mark "Public" trigger)
- Try to access this post from another server or another account

**Comment by edhelas** [comment] 2017-06-21 16:17
This feature is working, it seems to be a server configuration issue. Can you please be more precise with which server, domain, account it doesn't work and if possible provide me a test account, then I can reproduce the issue?

**Comment by kvaps** [comment] 2017-06-22 07:54
Hi, I used kvaps@xmpp.ru accound, and I created post on pubsub.feder8.ru using movim.feder8.ru server.
This is the post:
https://movim.feder8.ru/?post/pubsub.feder8.ru/feder8/b98e98f5-38b7-40d1-a087-b9df962306b3#

After it, I tried to access this post via nl.movim.eu and kvaps@movim.eu acount:
https://nl.movim.eu/?post/pubsub.feder8.ru/feder8/b98e98f5-38b7-40d1-a087-b9df962306b3

And I was success

**Comment by edhelas** [comment] 2018-05-06 22:01
Hi, is there some updates regarding this ticket?

**Comment by edhelas** [comment] 2018-11-18 10:00
Closing this ticket.

**Closed as completed by edhelas** 2018-11-18 10:00 UTC
Labels: more info
