### ISSUE TITLE
Can't initiate chat or launch adhoc commands on JIDs without localpart

### ISSUE THREAD

**Issue by nicolascedilnik** [movim/movim#1096] opened 2022-10-05 20:06 UTC
In movim it is currently impossible to add `xxxx.example.com` to the roster, or even to initiate a chat with this JID.
(but everything's fine if the component sends you a message first)

This is annoying for instance with the biboumi IRC gateway that provide adhoc commands.

**Comment by edhelas** [comment] 2022-10-06 20:46
Duplicate of #965

**Closed as completed by edhelas** 2022-10-06 20:46 UTC
Labels: duplicate
