### ISSUE TITLE
Movim ?post UI like button shouldn't let unlike the post by other users by owners.

### ISSUE THREAD

**Issue by maranda** [movim/movim#726] opened 2018-10-12 07:38 UTC
Owners have full privileges and can retract every post, you should explicitly let single likes be removed or only remove your own, Movim just attempts retracting every entry when unliking and if it's not restricted by the server it'll just do it.

**Comment by edhelas** [comment] 2018-11-28 22:56
I see a single retract sent when the post is unliked. 
Is it possible to get a XMPP trace to see what's wrongly done by Movim?
I don't get exactly what is the issue there.

**Comment by edhelas** [comment] 2020-10-01 16:42
I was not able to reproduce this issue so far, closing it.

**Closed as completed by edhelas** 2020-10-01 16:42 UTC
Labels: more info
