### ISSUE TITLE
Movim doesn't set "to" attribute in <stream:stream> after SASL, causing login loop

### ISSUE THREAD

**Issue by dos1** [movim/movim#685] opened 2018-08-12 06:18 UTC
I just installed Movim from the master branch and I can't connect to my server - login page goes into an infinite loop.

Turns out that after authenticating, Movim daemon sends malformed `stream:stream` tag: 
```
<stream:stream xmlns:stream="http://etherx.jabber.org/streams" version="1.0" xmlns="jabber:client" to="">
```

In turn, the server closes the connection, daemon shows `linker killed`, the frontend refreshes and the whole thing repeats over and over again.

The logs mentions the likely cause:
```
[12-Aug-2018 02:03:15 UTC] PHP Notice:  Trying to get property 'host' of non-object in /mnt/volume-fra1-01/www/movim/lib/moxl/src/Moxl/Xec/Payload/SASLSuccess.php on line 9
```

pep. on the MUC pointed to 167ff0348ad27079b81de06e32921ad370df8468 as a possible culprit

**Comment by dos1** [comment] 2018-08-16 03:42
Reverting 167ff03 fixes this issue.

**Comment by dos1** [comment] 2018-08-18 03:04
This seems to affect only new users - those that have never logged in before.

**Comment by dos1** [comment] 2018-08-19 02:10
Seems it's some race condition, or it doesn't happen with SQLite backend (I used MySQL earlier).

I was chasing this bug for a while until I realised that now I sometimes get into a login loop for a completely different reason :/

**Comment by edhelas** [comment] 2018-09-24 20:46
For the moment I'm not able to reproduce it, got an idea?

**Comment by dos1** [comment] 2018-09-24 20:47
Never seen it since switching to SQLite...

**Comment by edhelas** [comment] 2018-11-30 13:37
I'll close this ticket, I was not able to reproduce it.

**Comment by gauthier12** [comment] 2018-12-03 10:16
I've got the same problem with a fresh install.
The file php.log shows the message 
`PHP Notice:  Trying to get property of non-object in /var/www/movim/lib/moxl/src/Moxl/Xec/Payload/SASLSuccess.php on line 9`

and daemon log : 
`
movim.ERROR: Trying to get property of non-object [] []
déc. 03 11:06:43 gadem3.wuhu.eu movim[18650]: <stream:stream xmlns:stream="http://etherx.jabber.org/streams" version="1.0" xmlns="jabber:client" to=""> : sent to XMPP
déc. 03 11:06:43 gadem3.wuhu.eu movim[18650]: <?xml version='1.0'?><stream:stream id='1579938492459212289' version='1.0' xml:lang='en' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client'> : rec
déc. 03 11:06:43 gadem3.wuhu.eu movim[18650]: <stream:error><invalid-xml xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-streams'>Bad value of attribute &apos;
déc. 03 11:06:43 gadem3.wuhu.eu movim[18650]: bdRRzE5GxumDYFmLEWshZ7VRp4irlqQH : linker killed
`
would you have a hint of what to do to get it working ?

**Comment by edhelas** [comment] 2018-12-03 17:14
I'm closing the ticket, feel free to comment if you find the issue again.

**Comment by realkinetix** [comment] 2018-12-13 07:17
After much playing around the past couple of days, it appears that this issue comes up consistently for the first user after a fresh install and using mysql.  However, as mentioned above the issue doesn't seem to show up when using sqlite.  No other changes on a system have to occur except for switching out the DB for Movim.

**Closed as completed** 2018-12-13 21:38 UTC
